Agrego archivo CHANGELOG.txt
emarocha4/public-vault-ms pull request #2
Opened 2023-02-16 23:04 UTC by emarocha4

2023-02-16 23:12 UTC, eabugauch requested changes

2023-02-16 23:12 UTC, eabugauch commented on CHANGELOG.txt
> +- Se agrega archivo README.md.
Hay que colocar el numero de pull request y dividir por tipo de cambio un ejemplo: 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/25019749/219508913-8b9800f6-ba0b-46a2-91f2-6261994c619a.png">

2023-02-17 18:44 UTC, eabugauch commented
Cambiar nombre del PR colocar un titulo que coincida con lo que se esta agregando

2023-02-17 18:45 UTC, emarocha4 commented
> Cambiar nombre del PR colocar un titulo que coincida con lo que se esta agregando

Sugerencias?

2023-02-17 18:50 UTC, eabugauch requested changes

2023-02-17 18:50 UTC, eabugauch commented on CHANGELOG.txt
> +- Se agrega archivo README.md.
No veo solucionado esto @emarocha4

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +@RequestMapping("/api")
Cambiemos este nombre. Le pongamos /pci-vault

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    @PostMapping("/vault-cards")
Este que sea /card solamente

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    public ResponseEntity<String> createCard(@RequestBody String CardNumber) throws Exception {
el nombre del metodo no coincide con lo que se hace dice createCard y lo que hace es generar un token. buscar un nombre mas representativo de la funcion

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            LOGGER.severe("Error en myEndpoint: " + e.getMessage());
Aca mezclamos ingles y español elegir uno. Pongamos esto en ingles.

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    @GetMapping("/vault-cards/{token}")
cambiemos por /card/{token}

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            String number = cardService.getNumber(token);
esta variable local no hace falta que la creamos. Se puede poner directamente

return new ResponseEntity<>(cardService.getNumber(token), HttpStatus.OK);

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Agregemos logs por si llega a fallar en algo

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Agregemos logs por si llega a fallar en algo

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/models/Card.java
> +    // Getters & Setters
Borrar este comentario

2023-02-17 18:50 UTC, eabugauch commented on src/main/java/com/example/boveda/services/CardService.java
> +        SecretKeySpec secretKey = new SecretKeySpec(KEY.getBytes(), "AES");
Sacar el string "AES" a una constante ya que lo usamos en dos lugares diferentes aca y en la linea 39. Si en un futuro queremos cambiarlo directamente cambiamos la constante y no hay que estar cambiando en todos los lugares

2023-02-17 19:09 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +@RequestMapping("/api")
Done

2023-02-17 19:11 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    @PostMapping("/vault-cards")
Done

2023-02-17 19:13 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    public ResponseEntity<String> createCard(@RequestBody String CardNumber) throws Exception {
Done

2023-02-17 19:13 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            LOGGER.severe("Error en myEndpoint: " + e.getMessage());
Done

2023-02-17 19:14 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    @GetMapping("/vault-cards/{token}")
Done

2023-02-17 19:23 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            String number = cardService.getNumber(token);
Done

2023-02-17 19:27 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
Done

2023-02-17 19:28 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
Done

2023-02-17 19:28 UTC, emarocha4 commented on src/main/java/com/example/boveda/models/Card.java
> +    // Getters & Setters
Done

2023-02-17 19:46 UTC, emarocha4 commented on src/main/java/com/example/boveda/services/CardService.java
> +        SecretKeySpec secretKey = new SecretKeySpec(KEY.getBytes(), "AES");
Done

2023-02-17 20:10 UTC, emarocha4 commented on CHANGELOG.txt
> +- Se agrega archivo README.md.
Done

2023-02-21 15:36 UTC, eabugauch approved these changes

2023-02-21 15:36 UTC, eabugauch commented
LGTM 👌

2023-02-22 13:22 UTC, emarocha4 commented
**Método obtener token**

![image](https://user-images.githubusercontent.com/121126029/220631416-36cfb685-9498-450d-a550-b25c7e8301b1.png)


**Método obtener numero de tarjeta**

![image](https://user-images.githubusercontent.com/121126029/220631618-94c04156-24da-491a-b8a0-6abf60898c0d.png)


**Base de datos**

![image](https://user-images.githubusercontent.com/121126029/220631831-b110938c-ad43-4972-868e-3c234262fe83.png)

2023-02-22 13:23 UTC, merged