Adding unit test
emarocha4/public-vault-ms pull request #3
Opened 2023-02-24 15:20 UTC by emarocha4

2023-03-04 17:06 UTC, eabugauch requested changes

2023-03-04 17:06 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    public ResponseEntity<String> createCard(@RequestBody Card cardNumber) {
Cambiemos el objeto Card creemos uno especialmente para la request que sea CardRequest para no estar usando el del repositorio

2023-03-04 17:06 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            String key = System.getenv("KEY-VAULT");
Sacar a una constante el "KEY-VAULT"

2023-03-04 17:06 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
Busquemos una generalidad a la hora de responder fijate que aca haces ResponseEntity.badRequest y abajo haces lo mismo pero .status. Eleji uno de los dos y replicalo para tener una app integra

2023-03-04 17:06 UTC, eabugauch commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
Agreguemos un log

2023-03-04 17:06 UTC, eabugauch commented on src/main/java/com/example/boveda/services/CardService.java
> +            throw new IllegalArgumentException("La cadena de entrada no puede estar vacía.");
Estamos usando ingles en todo el proyecto los mensajes tienen que estar en ingles

2023-03-04 17:06 UTC, eabugauch commented on src/test/java/com/example/boveda/controllers/CardControllerTest.java
> +    public void testCreateCard(String cardNumber, String token, String key, String expectedValidation) throws Exception {
porque este dice public y el de abajo no?

2023-03-10 16:04 UTC, emarocha4 commented on src/test/java/com/example/boveda/controllers/CardControllerTest.java
> +    public void testCreateCard(String cardNumber, String token, String key, String expectedValidation) throws Exception {
Done

2023-03-10 16:08 UTC, emarocha4 commented on src/main/java/com/example/boveda/services/CardService.java
> +            throw new IllegalArgumentException("La cadena de entrada no puede estar vacía.");
Done

2023-03-10 16:15 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            return ResponseEntity.badRequest().body(e.getMessage());
Done

2023-03-10 16:28 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +            String key = System.getenv("KEY-VAULT");
Done

2023-03-10 18:56 UTC, emarocha4 commented on src/main/java/com/example/boveda/controllers/CardController.java
> +    public ResponseEntity<String> createCard(@RequestBody Card cardNumber) {
Done

2023-03-10 22:45 UTC, emarocha4 commented
![WhatsApp Image 2023-03-10 at 15 26 10](https://user-images.githubusercontent.com/121126029/224441933-203c777b-c65c-4585-9e14-09834a1d0e2f.jpeg)
![WhatsApp Image 2023-03-10 at 15 26 35](https://user-images.githubusercontent.com/121126029/224441946-49784441-bb00-4d5f-8224-5f7752743d0c.jpeg)
![WhatsApp Image 2023-03-10 at 15 27 00](https://user-images.githubusercontent.com/121126029/224442016-4c52b8cb-e83e-4db5-9e56-c86662deccc6.jpeg)
![WhatsApp Image 2023-03-10 at 15 27 17](https://user-images.githubusercontent.com/121126029/224441975-53b330fd-afff-4185-a7d9-1bac20edd400.jpeg)
![WhatsApp Image 2023-03-10 at 15 28 21](https://user-images.githubusercontent.com/121126029/224441992-cdabb159-f817-48c0-a18f-28f8d0a9b3fa.jpeg)
![image](https://user-images.githubusercontent.com/121126029/224442176-5635d5ed-4cab-4d1b-8115-9c1193938de0.png)

2023-03-10 22:47 UTC, merged